Repository caarlos0/starcharts, pull requests merged in 2021-07, with the labels that each got.

#121 feat: use etags to prevent rate limits
  go.mod
  go.sum
  internal/cache/cache.go
  internal/github/repo.go
  internal/github/repo_test.go
  internal/github/stars.go
  internal/github/stars_test.go
Labels: dependencies, enhancement

#126 feat: round robin several github tokens
  config/config.go
  internal/github/github.go
  internal/github/repo.go
  internal/github/repo_test.go
  internal/github/stars.go
  internal/github/stars_test.go
  internal/roundrobin/roudrobin.go
  internal/roundrobin/roundrobin_test.go
  main.go
Labels: enhancement, size/L

#127 Form for searching repo
  controller/index.go
  main.go
  static/styles.css
  static/templates/index.html
Labels: size/M
